TodoList : Implement storage system
AY2021S1-CS2103T-F12-3/tp pull request #308
Opened 2020-10-20 11:21 UTC by davidcaiqifan

Fixes #179 
- Adds mutiple classes to faciliate storage of todolist
- Integrates storage with rest of code

2020-10-20 12:17 UTC, jonasngs requested changes
The code quality is good, the code is readable and understandable and conforms to the implementation of Module Storage and Contact Storage. It LGTM, albeit some changes needed.

2020-10-20 12:17 UTC, jonasngs commented on src/main/java/seedu/address/storage/StorageManager.java
> +        logger.fine("Attempting to write to data file: " + filePath);
The comment from above could be useful here as well, we could refine the logger message to be something more specific and meaningful.

2020-10-20 12:17 UTC, jonasngs commented on src/main/java/seedu/address/storage/JsonAdaptedTask.java
> +    public JsonAdaptedTask(Task source) {
I think the implementation of this constructor can be improved. For a Task object, the Date, Priority and Tag fields are optional and the below implementation might result in a NullPointerException, for eg, invoking getPriority().get() might return null.

2020-10-21 08:38 UTC, davidcaiqifan commented on src/main/java/seedu/address/storage/JsonAdaptedToDoList.java
> +package seedu.address.storage;
It was unnecessary. Thanks for pointing that out!

2020-10-22 07:46 UTC, jonasngs approved these changes

2020-10-22 07:46 UTC, jonasngs commented
LGTM.

2020-10-22 07:49 UTC, merged